In [1]:
import pandas as pd

In [15]:
data = pd.read_csv('C:/Users/slugg/Documents/GitHub/three_idiot/전처리_데이터/morphed_data.csv', encoding='cp949', index_col=0)
data

                                                        0  1
0       드라이기 사용 후 머리카락 윤기 그동안 사용 드라이기 갑자기 고장 나다 다시 드라이...  1
1       곱슬 숱 많다 머리 어깨 살짝 가다 릴 정도 기장 말리다 시간 정도 걸리다 물론 뜨...  1
2       일단 ㅋㅋ ㅋ 정말 바람 쎄다 좋다 여름 ㅋㅋ ㅋ 선풍기 대신 쓰다 되다 시원 장점...  1
3       미용실 드라이 하다 머리 결도 좋다 보이다 머리 차분 하다 사용 샴푸 트리트먼트 차...  1
4       미용실 추천 하다 가성 비 드라이기 나다 돈 내산리 뷰 다 미용실 드라이기 잘 마르...  1
...                                                   ... ..
290378                     일주일 다 되다 오다 말다 연락 없다 그렇다 리뷰 쓰다  0
290379                                               굳 감사  1
290380                                    기사 너무 감사 드리다 ^^  1
290381                                      빠르다 설치다 감사 하다  1
290382                                           잘 설치다 하다  1

[290383 rows x 2 columns]

In [16]:
good = data[data.iloc[:, 1]==1]
bad = data[data.iloc[:, 1]==0]

In [17]:
bad

                                                        0  1
29                                                사용 때 너무  0
30                                   두피 보호 아이 머리 말리 두피 타다  0
31                                             소리 넘다 시끄럽다  0
32      기대다 하다 말다 기존 쓰다 세기 그만치 셀 생각 구매 바람 세기 일반 드라이기 별...  0
33      요란 하다 소리 약 한 바라다 상 평 속다 기분 비다 수레 소리 요란 약하다 머리 ...  0
...                                                   ... ..
290363                                        한 모터 고장 불만족  0
290367                      원룸 설치다 하다 탈수 하다 때 소음 너무 크다 ㅠㅠ  0
290373  배송 친절 하다 빨래 잘 안되다 신청 하다 잘 하다 고맙다 근본적 빨래 안되다 요즘...  0
290376          최악 마루 바닥 틈 다 망가 설치 하다 책임 어 떨다 없다 그냥 가다 최악  0
290378                     일주일 다 되다 오다 말다 연락 없다 그렇다 리뷰 쓰다  0

[27827 rows x 2 columns]

In [19]:
sampled_good = good.sample(n=len(bad)*3, replace=False)

print(len(sampled_good))
print(sampled_good)

83481
                                                        0  1
80776                            진짜 좋다 싸게 산 같다 그립다 타격감 굳굳  1
61176                                   전 비슷 상품 써 불편 한 없다  1
904                       기숙사 보내다 잘 작동 되다 하다 일단 잘 사용 좋다 편  1
248673      노트 이제 품다 터 울트라 선택 지퍼 가 있다 만족 카드 수납 돈 떨어뜨리다 안심  1
145683  마지막 미니 아이폰 미니 사용 바꾸다 역시 여자 핑크 ㅋㅋ ㅋㅋ 계속 아이폰 쓰다 ...  1
...                                                   ... ..
211243  미라클 로마 리미티드 지퍼 다이어리 핸드 트랩 휴대폰 케이스 지폐 지갑 간편 하다 ...  1
123322  노트북 게임 욕심 없다 게임 하다 이것저것 알아보다 검색 해보다 찜 콩 하다 외관 ...  1
53619                          설치다 기사 정말 너무 친절 요 설치다 잘 하다  1
98426                         좋다 설치다 오른쪽 숫자 키 패트 없다 ㅋㅋ ㅋㅋ  1
2335    똑같다 은제 품다 쓰다 고장 나다 구매 하다 잘 쓰다 기억 있다 고민 알다 바로 구...  1

[83481 rows x 2 columns]

In [20]:
all_data = pd.concat([sampled_good, bad], axis=0)
all_data

                                                        0  1
80776                            진짜 좋다 싸게 산 같다 그립다 타격감 굳굳  1
61176                                   전 비슷 상품 써 불편 한 없다  1
904                       기숙사 보내다 잘 작동 되다 하다 일단 잘 사용 좋다 편  1
248673      노트 이제 품다 터 울트라 선택 지퍼 가 있다 만족 카드 수납 돈 떨어뜨리다 안심  1
145683  마지막 미니 아이폰 미니 사용 바꾸다 역시 여자 핑크 ㅋㅋ ㅋㅋ 계속 아이폰 쓰다 ...  1
...                                                   ... ..
290363                                        한 모터 고장 불만족  0
290367                      원룸 설치다 하다 탈수 하다 때 소음 너무 크다 ㅠㅠ  0
290373  배송 친절 하다 빨래 잘 안되다 신청 하다 잘 하다 고맙다 근본적 빨래 안되다 요즘...  0
290376          최악 마루 바닥 틈 다 망가 설치 하다 책임 어 떨다 없다 그냥 가다 최악  0
290378                     일주일 다 되다 오다 말다 연락 없다 그렇다 리뷰 쓰다  0

[111308 rows x 2 columns]

In [21]:
all_data = all_data.sample(frac=1).reset_index(drop=True)
all_data

                                                        0  1
0       진짜 좋다 살짝 걱정 구매 하다 진짜 잘 같다 전 쓰다 드라 업소 용 괜찮다 바꾸다...  1
1       개판 설치 초록 화면 소리 안 나오다 고객센터 대응 아주 가관 고객센터 전화 한번 ...  0
2                                    저렴 한가 격 비하다 품질 정말 좋다  1
3       안사 추천 드리다 끼 파손 되다 케이스 생각 너무 얇다 끼 파손 되다 케이스 처음 ...  0
4                                               튼튼 예쁘다 ^^  1
...                                                   ... ..
111303  굿 여러모로 편하다 좋다 블로그 작성 좋다 키보드 소리 여러 의견 있다 전문 매니아...  1
111304            키 가 원하다 말 다른 버전 사세 조용 하긴 하다 너무 켜다 감다 없다  1
111305  미니 사이즈 마지막 고사 아이폰 색상 존 예 여성 추천 구매 쓰다 바꾸다 손 작고 ...  1
111306  처음 중소기업 티비 사다 되다 데우다 다르다 아주 잘 사다 생각 중소기업 제품 무시...  1
111307                          완전 최고 ㅋㅋ ㅋㅋ ㅋ 조명 음향 아주 좋다  1

[111308 rows x 2 columns]

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(all_data.iloc[:, 0], all_data.iloc[:, 1], stratify=all_data.iloc[:, 1])

In [25]:
train_data = pd.concat([X_train, y_train], axis=1).reset_index(drop=True)
test_data = pd.concat([X_test, y_test], axis=1).reset_index(drop=True)

train_data.to_csv('C:/Users/slugg/Documents/GitHub/three_idiot/전처리_데이터/train.csv', encoding='cp949', index=0)
test_data.to_csv('C:/Users/slugg/Documents/GitHub/three_idiot/전처리_데이터/test.csv', encoding='cp949', index=0)